# Generated by Django 2.0 on 2018-04-04 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('ac_number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ac_ttaf', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ac_ttel', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ac_tter', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'aircraft',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Charter',
            fields=[
                ('char_trip', models.IntegerField(primary_key=True, serialize=False)),
                ('char_date', models.DateField(blank=True, null=True)),
                ('char_destination', models.CharField(blank=True, max_length=3, null=True)),
                ('char_distance', models.IntegerField(blank=True, null=True)),
                ('char_hours_flown', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('char_hours_wait', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('char_fuel_gallons', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('char_oil_qts', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'charter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_code', models.IntegerField(primary_key=True, serialize=False)),
                ('cus_lname', models.CharField(blank=True, max_length=15, null=True)),
                ('cus_fname', models.CharField(blank=True, max_length=15, null=True)),
                ('cus_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('cus_areacode', models.CharField(blank=True, max_length=3, null=True)),
                ('cus_phone', models.CharField(blank=True, max_length=8, null=True)),
                ('cus_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_num', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_title', models.CharField(blank=True, max_length=4, null=True)),
                ('emp_lname', models.CharField(blank=True, max_length=15, null=True)),
                ('emp_fname', models.CharField(blank=True, max_length=15, null=True)),
                ('emp_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('emp_dob', models.DateField(blank=True, null=True)),
                ('emp_hire_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('mod_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(blank=True, max_length=15, null=True)),
                ('mod_name', models.CharField(blank=True, max_length=20, null=True)),
                ('mod_seats', models.IntegerField(blank=True, null=True)),
                ('mod_chg_mile', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rtg_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('rtg_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('char_trip', models.ForeignKey(db_column='char_trip', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='airline.Charter')),
                ('crew_job', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'crew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Earnedrating',
            fields=[
                ('emp_num', models.ForeignKey(db_column='emp_num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='airline.Employee')),
                ('earnrtg_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'earnedrating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('emp_num', models.ForeignKey(db_column='emp_num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='airline.Employee')),
                ('pil_license', models.CharField(blank=True, max_length=25, null=True)),
                ('pil_ratings', models.CharField(blank=True, max_length=30, null=True)),
                ('pil_med_type', models.CharField(blank=True, max_length=1, null=True)),
                ('pil_med_date', models.DateField(blank=True, null=True)),
                ('pil_pt135_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pilot',
                'managed': False,
            },
        ),
    ]
